service: cake-ordering-system

plugins:
  - serverless-pseudo-parameters
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource:
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/ordersTable

    - Effect: Allow
      Action:
        - kinesis:PutRecord
      Resource:
        - arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/order-events

    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource:
        - "*"
      Condition:
        StringEquals:
          ses:FromAddress:
            - mohovkm@yandex.ru

    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - arn:aws:sqs:#{AWS::Region}:#{AWS::AccountId}:deliveryServiceQueue
        - arn:aws:sqs:#{AWS::Region}:#{AWS::AccountId}:customerServiceQueue

functions:
  create_order:
    handler: app/handler.create_order
    events:
      - http:
          path: /order
          method: post
    environment:
      DYNAMO_ORDER_TABLE_NAME: ordersTable
      KINESIS_ORDER_STREAM_NAME: order-events

  fulfill_order:
    handler: app/handler.fulfill_order
    events:
      - http:
          path: /order/fulfill
          method: post
    environment:
      DYNAMO_ORDER_TABLE_NAME: ordersTable
      KINESIS_ORDER_STREAM_NAME: order-events

  notify_external_parties:
    handler: app/handler.notify_external_parties
    events:
      - stream:
          arn: arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/order-events
    environment:
      REGION: ${self:provider.region}
      CAKE_PRODUCER_EMAIL: zsprogrammer3@gmail.com
      ORDERING_SYSTEM_EMAIL: mohovkm@yandex.ru
      DELIVERY_COMPANY_QUEUE:
        Ref: deliveryServiceQueue
      DYNAMO_ORDER_TABLE_NAME: ordersTable
      KINESIS_ORDER_STREAM_NAME: order-events

  notify_delivery_company:
    handler: app/handler.notify_delivery_company
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - deliveryServiceQueue
              - Arn
          batchSize: 1

  order_delivered:
    handler: app/handler.order_delivered
    events:
      - http:
          path: /order/delivered
          method: post
    environment:
      REGION: ${self:provider.region}
      DYNAMO_ORDER_TABLE_NAME: ordersTable
      KINESIS_ORDER_STREAM_NAME: order-events
      DELIVERY_COMPANY_QUEUE:
        Ref: deliveryServiceQueue
      CUSTOMER_SERVICE_QUEUE:
        Ref: customerServiceQueue

  notify_customer_service:
    handler: app/handler.notify_customer_service
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - customerServiceQueue
              - Arn
          batchSize: 1

resources:
  Resources:
    orderEventsStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: order-events
        ShardCount: 1

    orderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ordersTable
        AttributeDefinitions:
          - AttributeName: "order_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "order_id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

    deliveryServiceQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: deliveryServiceQueue

    customerServiceQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: customerServiceQueue
