service: cake-ordering-system

plugins:
  - serverless-pseudo-parameters
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource:
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/ordersTable

    - Effect: Allow
      Action:
        - kinesis:PutRecord
      Resource:
        - arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/order-events

    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource:
        - "*"
      Condition:
        StringEquals:
          ses:FromAddress:
            - mohovkm@yandex.ru

functions:
  create_order:
    handler: app/handler.create_order
    events:
      - http:
          path: /order
          method: post
    environment:
      DYNAMO_ORDER_TABLE_NAME: ordersTable
      KINESIS_ORDER_STREAM_NAME: order-events

  fulfill_order:
    handler: app/handler.fulfill_order
    events:
      - http:
          path: /order/fulfill
          method: post
    environment:
      DYNAMO_ORDER_TABLE_NAME: ordersTable
      KINESIS_ORDER_STREAM_NAME: order-events

  notify_cake_producer:
    handler: app/handler.notify_cake_producer
    events:
      - stream:
          arn: arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/order-events
    environment:
      REGION: ${self:provider.region}
      CAKE_PRODUCER_EMAIL: zsprogrammer3@gmail.com
      ORDERING_SYSTEM_EMAIL: mohovkm@yandex.ru

resources:
  Resources:
    orderEventsStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: order-events
        ShardCount: 1

    orderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ordersTable
        AttributeDefinitions:
          - AttributeName: "order_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "order_id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
